name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install python

      - name: install girara
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install ./girara.rb

      - name: install zathura
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install ./zathura.rb

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install python

      - name: install girara
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install ./girara.rb

      - name: install zathura
        run: |
          eval "$($(brew --prefix)/bin/brew shellenv)"
          brew install ./zathura.rb
